#!/usr/bin/env python3
"""Copy CLAUDE.md into the rules files Google Antigravity reads.

Claude Code reads CLAUDE.md at the repository root. Antigravity reads
`.agents/rules/*.md` (and AGENTS.md), and it TRUNCATES a rule file that is too
long — a 39 KB copy of CLAUDE.md silently loses everything past "The local
assistant". So the copy is split into parts small enough to survive, each
marked `trigger: always_on` so it is loaded unconditionally rather than only
when the model decides it is relevant.

Run this after any change to CLAUDE.md:

    python3 .agents/sync-rules.py
"""

from pathlib import Path

# MARK: - Settings

MAX_CHARS = 10000          # per part; well under the size at which a rule is cut
REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "CLAUDE.md"
RULES = Path(__file__).resolve().parent / "rules"


# MARK: - Functions

def split_into_sections(text):
    """Break the document at its top-level '## ' headings."""
    sections = []
    current = []
    for line in text.splitlines(keepends=True):
        if line.startswith("## ") and current:
            sections.append("".join(current))
            current = [line]
        else:
            current.append(line)
    if current:
        sections.append("".join(current))
    return sections


def split_oversized(section):
    """Break one over-long section at blank lines, into pieces under the cap.

    Every piece after the first repeats the section's heading, marked
    "(continued)", so a part that starts mid-section still says what it is part
    of instead of beginning with an orphaned numbered item.
    """
    if len(section) <= MAX_CHARS:
        return [section]
    heading = section.splitlines()[0].strip()
    continuation = f"{heading} (continued)\n\n"
    pieces = []
    current = ""
    for paragraph in section.split("\n\n"):
        candidate = paragraph if not current else current + "\n\n" + paragraph
        if len(candidate) > MAX_CHARS and current:
            pieces.append(current)
            current = continuation + paragraph
        else:
            current = candidate
    if current:
        pieces.append(current)
    return pieces


def pack_into_parts(sections):
    """Fill each part with as many whole sections as fit under the cap."""
    parts = []
    current = ""
    for section in sections:
        for piece in split_oversized(section):
            candidate = current + piece
            if len(candidate) > MAX_CHARS and current:
                parts.append(current)
                current = piece
            else:
                current = candidate
    if current:
        parts.append(current)
    return parts


def title_of(part):
    """The first heading in a part, used as its description."""
    for line in part.splitlines():
        if line.startswith("#"):
            return line.lstrip("# ").strip()
    return "Plantoir project instructions"


def write_parts(parts):
    RULES.mkdir(parents=True, exist_ok=True)
    for stale in RULES.glob("*.md"):
        stale.unlink()
    written = []
    for index, part in enumerate(parts, start=1):
        path = RULES / f"{index:02d}-claude-md.md"
        # Quoted, because a bare colon in a YAML value makes the whole file
        # unparseable and Antigravity then skips the rule without saying so.
        description = f"Plantoir project rules, part {index} of {len(parts)} - {title_of(part)}"
        header = (
            "---\n"
            "trigger: always_on\n"
            "glob:\n"
            f'description: "{description}"\n'
            "---\n\n"
            f"<!-- Part {index} of {len(parts)} of a COPY of CLAUDE.md. Do not edit this file:\n"
            "     edit CLAUDE.md, then run `python3 .agents/sync-rules.py`. -->\n\n"
        )
        path.write_text(header + part.rstrip() + "\n")
        written.append(path)
    return written


def main():
    parts = pack_into_parts(split_into_sections(SOURCE.read_text()))
    for path in write_parts(parts):
        print(f"{path.relative_to(REPO)}  {len(path.read_text()):>6} chars")


main()
